version: '3.5'
services:
  php-fpm:
    build:
      context: docker/php-fpm
      dockerfile: Dockerfile
    environment:
      XDEBUG_CONFIG: "remote_host=host.docker.internal remote_enable=1"
      PHP_IDE_CONFIG: "serverName=docker-master"
    volumes:
      - ./:/app
    depends_on:
      - postgres
  postgres:
    build:
      context: docker/postgress
      dockerfile: Dockerfile
    command: -c 'log_min_messages=debug5'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - "5432:5432"
volumes:
  postgres: